apiVersion: apps/v1
kind: Deployment
metadata:
  name: mayapp-deployment
  labels:
    tier: front-end
    app: nginx
spec:
  template:
    metadata:
      name: nginx
      namespace: demo
      labels:
        env: production
        type: app
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end  